# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(496, 527)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabs = QtGui.QTabWidget(Dialog)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.twitch_tab = QtGui.QWidget()
        self.twitch_tab.setWhatsThis(_fromUtf8(""))
        self.twitch_tab.setAccessibleName(_fromUtf8(""))
        self.twitch_tab.setAutoFillBackground(False)
        self.twitch_tab.setObjectName(_fromUtf8("twitch_tab"))
        self.layoutWidget = QtGui.QWidget(self.twitch_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 441, 420))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtGui.QFormLayout.WrapAllRows)
        self.formLayout.setContentsMargins(-1, -1, 15, -1)
        self.formLayout.setHorizontalSpacing(25)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.username_text = QtGui.QLineEdit(self.layoutWidget)
        self.username_text.setObjectName(_fromUtf8("username_text"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.username_text)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.oauth_text = QtGui.QLineEdit(self.layoutWidget)
        self.oauth_text.setObjectName(_fromUtf8("oauth_text"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.oauth_text)
        self.oauth_btn = QtGui.QPushButton(self.layoutWidget)
        self.oauth_btn.setObjectName(_fromUtf8("oauth_btn"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.oauth_btn)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.channel_text = QtGui.QLineEdit(self.layoutWidget)
        self.channel_text.setObjectName(_fromUtf8("channel_text"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.channel_text)
        self.test_connection_btn_2 = QtGui.QPushButton(self.layoutWidget)
        self.test_connection_btn_2.setObjectName(_fromUtf8("test_connection_btn_2"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.test_connection_btn_2)
        self.console_text = QtGui.QTextEdit(self.layoutWidget)
        self.console_text.setReadOnly(True)
        self.console_text.setObjectName(_fromUtf8("console_text"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.console_text)
        self.tabs.addTab(self.twitch_tab, _fromUtf8(""))
        self.hue_tab = QtGui.QWidget()
        self.hue_tab.setObjectName(_fromUtf8("hue_tab"))
        self.layoutWidget1 = QtGui.QWidget(self.hue_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 250, 431, 62))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.color_picker_2_btn = QtGui.QPushButton(self.layoutWidget1)
        self.color_picker_2_btn.setObjectName(_fromUtf8("color_picker_2_btn"))
        self.gridLayout_2.addWidget(self.color_picker_2_btn, 0, 4, 1, 1)
        self.flash_color_2_graphic = QtGui.QGraphicsView(self.layoutWidget1)
        self.flash_color_2_graphic.setMaximumSize(QtCore.QSize(25, 25))
        self.flash_color_2_graphic.setFrameShape(QtGui.QFrame.Box)
        self.flash_color_2_graphic.setFrameShadow(QtGui.QFrame.Plain)
        self.flash_color_2_graphic.setLineWidth(1)
        self.flash_color_2_graphic.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.flash_color_2_graphic.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.flash_color_2_graphic.setForegroundBrush(brush)
        self.flash_color_2_graphic.setSceneRect(QtCore.QRectF(0.0, 0.0, 5.0, 5.0))
        self.flash_color_2_graphic.setOptimizationFlags(QtGui.QGraphicsView.DontSavePainterState)
        self.flash_color_2_graphic.setObjectName(_fromUtf8("flash_color_2_graphic"))
        self.gridLayout_2.addWidget(self.flash_color_2_graphic, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.flash_color_2 = QtGui.QLineEdit(self.layoutWidget1)
        self.flash_color_2.setObjectName(_fromUtf8("flash_color_2"))
        self.gridLayout_2.addWidget(self.flash_color_2, 0, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.hue_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 431, 71))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.hue_ip_text = QtGui.QLineEdit(self.layoutWidget2)
        self.hue_ip_text.setObjectName(_fromUtf8("hue_ip_text"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.hue_ip_text)
        self.bridge_detect_btn = QtGui.QPushButton(self.layoutWidget2)
        self.bridge_detect_btn.setObjectName(_fromUtf8("bridge_detect_btn"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.bridge_detect_btn)
        self.layoutWidget3 = QtGui.QWidget(self.hue_tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 90, 431, 82))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.formLayout_3 = QtGui.QFormLayout(self.layoutWidget3)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.fetch_groups_button = QtGui.QPushButton(self.layoutWidget3)
        self.fetch_groups_button.setObjectName(_fromUtf8("fetch_groups_button"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.fetch_groups_button)
        self.hue_group_combo = QtGui.QComboBox(self.layoutWidget3)
        self.hue_group_combo.setObjectName(_fromUtf8("hue_group_combo"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.hue_group_combo)
        self.layoutWidget4 = QtGui.QWidget(self.hue_tab)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 180, 431, 62))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.color_picker_1_btn = QtGui.QPushButton(self.layoutWidget4)
        self.color_picker_1_btn.setObjectName(_fromUtf8("color_picker_1_btn"))
        self.gridLayout.addWidget(self.color_picker_1_btn, 0, 4, 1, 1)
        self.flash_color_1_graphic = QtGui.QGraphicsView(self.layoutWidget4)
        self.flash_color_1_graphic.setMaximumSize(QtCore.QSize(25, 25))
        self.flash_color_1_graphic.setFrameShape(QtGui.QFrame.Box)
        self.flash_color_1_graphic.setFrameShadow(QtGui.QFrame.Plain)
        self.flash_color_1_graphic.setLineWidth(1)
        self.flash_color_1_graphic.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.flash_color_1_graphic.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.flash_color_1_graphic.setForegroundBrush(brush)
        self.flash_color_1_graphic.setSceneRect(QtCore.QRectF(0.0, 0.0, 5.0, 5.0))
        self.flash_color_1_graphic.setOptimizationFlags(QtGui.QGraphicsView.DontSavePainterState)
        self.flash_color_1_graphic.setObjectName(_fromUtf8("flash_color_1_graphic"))
        self.gridLayout.addWidget(self.flash_color_1_graphic, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.flash_color_1 = QtGui.QLineEdit(self.layoutWidget4)
        self.flash_color_1.setObjectName(_fromUtf8("flash_color_1"))
        self.gridLayout.addWidget(self.flash_color_1, 0, 1, 1, 1)
        self.layoutWidget5 = QtGui.QWidget(self.hue_tab)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 320, 281, 21))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.formLayout_4 = QtGui.QFormLayout(self.layoutWidget5)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_8 = QtGui.QLabel(self.layoutWidget5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.flash_speed_slider = QtGui.QSlider(self.layoutWidget5)
        self.flash_speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.flash_speed_slider.setObjectName(_fromUtf8("flash_speed_slider"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.flash_speed_slider)
        self.layoutWidget6 = QtGui.QWidget(self.hue_tab)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 350, 122, 24))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.formLayout_5 = QtGui.QFormLayout(self.layoutWidget6)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_9 = QtGui.QLabel(self.layoutWidget6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.hue_flash_count_spin_box = QtGui.QSpinBox(self.layoutWidget6)
        self.hue_flash_count_spin_box.setObjectName(_fromUtf8("hue_flash_count_spin_box"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.hue_flash_count_spin_box)
        self.layoutWidget7 = QtGui.QWidget(self.hue_tab)
        self.layoutWidget7.setGeometry(QtCore.QRect(340, 310, 108, 65))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.formLayout_6 = QtGui.QFormLayout(self.layoutWidget7)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.test_connection_btn = QtGui.QPushButton(self.layoutWidget7)
        self.test_connection_btn.setObjectName(_fromUtf8("test_connection_btn"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.test_connection_btn)
        self.test_flash_button = QtGui.QPushButton(self.layoutWidget7)
        self.test_flash_button.setObjectName(_fromUtf8("test_flash_button"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.test_flash_button)
        self.tabs.addTab(self.hue_tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabs)
        self.dialog_buttons = QtGui.QDialogButtonBox(Dialog)
        self.dialog_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.dialog_buttons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Save)
        self.dialog_buttons.setObjectName(_fromUtf8("dialog_buttons"))
        self.verticalLayout.addWidget(self.dialog_buttons)

        self.retranslateUi(Dialog)
        self.tabs.setCurrentIndex(1)
        QtCore.QObject.connect(self.dialog_buttons, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.dialog_buttons, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.tabs.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.label.setText(_translate("Dialog", "Username", None))
        self.label_3.setText(_translate("Dialog", "OAuth", None))
        self.oauth_text.setText(_translate("Dialog", "< Enter existing OAuth token or click to obtain a new one. >", None))
        self.oauth_btn.setText(_translate("Dialog", "Get OAuth Token", None))
        self.label_2.setText(_translate("Dialog", "Channel", None))
        self.test_connection_btn_2.setText(_translate("Dialog", "Test Connection", None))
        self.tabs.setTabText(self.tabs.indexOf(self.twitch_tab), _translate("Dialog", "Twitch", None))
        self.color_picker_2_btn.setText(_translate("Dialog", "Color Picker", None))
        self.label_7.setText(_translate("Dialog", "Flash Color 2", None))
        self.label_4.setText(_translate("Dialog", "Hue Bridge IP", None))
        self.hue_ip_text.setText(_translate("Dialog", "< Get IP via the mobile app, or click to auto detect. >", None))
        self.bridge_detect_btn.setText(_translate("Dialog", "Detect Bridge IP", None))
        self.label_5.setText(_translate("Dialog", "Hue Group", None))
        self.fetch_groups_button.setText(_translate("Dialog", "Fetch Groups", None))
        self.color_picker_1_btn.setText(_translate("Dialog", "Color Picker", None))
        self.label_6.setText(_translate("Dialog", "Flash Color 1", None))
        self.label_8.setText(_translate("Dialog", "Flash Speed", None))
        self.label_9.setText(_translate("Dialog", "Flash Count", None))
        self.test_connection_btn.setText(_translate("Dialog", "Test Connection", None))
        self.test_flash_button.setText(_translate("Dialog", "Test Flash", None))
        self.tabs.setTabText(self.tabs.indexOf(self.hue_tab), _translate("Dialog", "Hue", None))

