# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(496, 501)
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabs = QtGui.QTabWidget(Dialog)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.twitch_tab = QtGui.QWidget()
        self.twitch_tab.setWhatsThis(_fromUtf8(""))
        self.twitch_tab.setAccessibleName(_fromUtf8(""))
        self.twitch_tab.setAutoFillBackground(False)
        self.twitch_tab.setObjectName(_fromUtf8("twitch_tab"))
        self.layoutWidget = QtGui.QWidget(self.twitch_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 11, 451, 401))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.username_text = QtGui.QLineEdit(self.layoutWidget)
        self.username_text.setObjectName(_fromUtf8("username_text"))
        self.horizontalLayout_4.addWidget(self.username_text)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.oauth_text = QtGui.QLineEdit(self.layoutWidget)
        self.oauth_text.setText(_fromUtf8(""))
        self.oauth_text.setObjectName(_fromUtf8("oauth_text"))
        self.horizontalLayout_3.addWidget(self.oauth_text)
        self.oauth_btn = QtGui.QPushButton(self.layoutWidget)
        self.oauth_btn.setObjectName(_fromUtf8("oauth_btn"))
        self.horizontalLayout_3.addWidget(self.oauth_btn)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.channel_text = QtGui.QLineEdit(self.layoutWidget)
        self.channel_text.setReadOnly(False)
        self.channel_text.setObjectName(_fromUtf8("channel_text"))
        self.horizontalLayout_2.addWidget(self.channel_text)
        self.unlock_channel = QtGui.QCheckBox(self.layoutWidget)
        self.unlock_channel.setObjectName(_fromUtf8("unlock_channel"))
        self.horizontalLayout_2.addWidget(self.unlock_channel)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.test_connection_btn_2 = QtGui.QPushButton(self.layoutWidget)
        self.test_connection_btn_2.setObjectName(_fromUtf8("test_connection_btn_2"))
        self.gridLayout_6.addWidget(self.test_connection_btn_2, 3, 0, 1, 1)
        self.console_text = QtGui.QTextEdit(self.layoutWidget)
        self.console_text.setEnabled(False)
        self.console_text.setReadOnly(True)
        self.console_text.setObjectName(_fromUtf8("console_text"))
        self.gridLayout_6.addWidget(self.console_text, 4, 0, 1, 1)
        self.tabs.addTab(self.twitch_tab, _fromUtf8(""))
        self.hue_tab = QtGui.QWidget()
        self.hue_tab.setObjectName(_fromUtf8("hue_tab"))
        self.layoutWidget1 = QtGui.QWidget(self.hue_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 451, 401))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget1)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.hue_bridge_config = QtGui.QFormLayout()
        self.hue_bridge_config.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.hue_bridge_config.setObjectName(_fromUtf8("hue_bridge_config"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.hue_ip_text = QtGui.QLineEdit(self.groupBox)
        self.hue_ip_text.setMaximumSize(QtCore.QSize(150, 16777215))
        self.hue_ip_text.setText(_fromUtf8(""))
        self.hue_ip_text.setReadOnly(False)
        self.hue_ip_text.setObjectName(_fromUtf8("hue_ip_text"))
        self.horizontalLayout.addWidget(self.hue_ip_text)
        self.bridge_detect_btn = QtGui.QPushButton(self.groupBox)
        self.bridge_detect_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.bridge_detect_btn.setObjectName(_fromUtf8("bridge_detect_btn"))
        self.horizontalLayout.addWidget(self.bridge_detect_btn)
        self.unlock_2_check_2 = QtGui.QCheckBox(self.groupBox)
        self.unlock_2_check_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unlock_2_check_2.setObjectName(_fromUtf8("unlock_2_check_2"))
        self.horizontalLayout.addWidget(self.unlock_2_check_2)
        self.hue_bridge_config.setWidget(0, QtGui.QFormLayout.FieldRole, self.groupBox)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.hue_bridge_config)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.flash_1_web = QtWebKit.QWebView(self.layoutWidget1)
        self.flash_1_web.setMaximumSize(QtCore.QSize(40, 40))
        self.flash_1_web.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.flash_1_web.setObjectName(_fromUtf8("flash_1_web"))
        self.gridLayout.addWidget(self.flash_1_web, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.color_picker_1_btn = QtGui.QPushButton(self.layoutWidget1)
        self.color_picker_1_btn.setObjectName(_fromUtf8("color_picker_1_btn"))
        self.gridLayout.addWidget(self.color_picker_1_btn, 0, 4, 1, 1)
        self.flash_color_1 = QtGui.QLineEdit(self.layoutWidget1)
        self.flash_color_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.flash_color_1.setReadOnly(True)
        self.flash_color_1.setObjectName(_fromUtf8("flash_color_1"))
        self.gridLayout.addWidget(self.flash_color_1, 0, 1, 1, 1)
        self.unlock_1_check = QtGui.QCheckBox(self.layoutWidget1)
        self.unlock_1_check.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unlock_1_check.setObjectName(_fromUtf8("unlock_1_check"))
        self.gridLayout.addWidget(self.unlock_1_check, 0, 2, 1, 1)
        self.formLayout.setLayout(2, QtGui.QFormLayout.SpanningRole, self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.unlock_2_check = QtGui.QCheckBox(self.layoutWidget1)
        self.unlock_2_check.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unlock_2_check.setObjectName(_fromUtf8("unlock_2_check"))
        self.gridLayout_2.addWidget(self.unlock_2_check, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.flash_color_2 = QtGui.QLineEdit(self.layoutWidget1)
        self.flash_color_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.flash_color_2.setReadOnly(True)
        self.flash_color_2.setObjectName(_fromUtf8("flash_color_2"))
        self.gridLayout_2.addWidget(self.flash_color_2, 0, 1, 1, 1)
        self.color_picker_2_btn = QtGui.QPushButton(self.layoutWidget1)
        self.color_picker_2_btn.setObjectName(_fromUtf8("color_picker_2_btn"))
        self.gridLayout_2.addWidget(self.color_picker_2_btn, 0, 4, 1, 1)
        self.flash_2_web = QtWebKit.QWebView(self.layoutWidget1)
        self.flash_2_web.setMaximumSize(QtCore.QSize(40, 40))
        self.flash_2_web.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.flash_2_web.setObjectName(_fromUtf8("flash_2_web"))
        self.gridLayout_2.addWidget(self.flash_2_web, 0, 3, 1, 1)
        self.formLayout.setLayout(3, QtGui.QFormLayout.SpanningRole, self.gridLayout_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.flash_speed_slider = QtGui.QSlider(self.layoutWidget1)
        self.flash_speed_slider.setMaximumSize(QtCore.QSize(200, 16777215))
        self.flash_speed_slider.setMinimum(1)
        self.flash_speed_slider.setMaximum(3)
        self.flash_speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.flash_speed_slider.setObjectName(_fromUtf8("flash_speed_slider"))
        self.gridLayout_4.addWidget(self.flash_speed_slider, 0, 1, 1, 1)
        self.formLayout.setLayout(5, QtGui.QFormLayout.LabelRole, self.gridLayout_4)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.hue_flash_count_spin_box = QtGui.QSpinBox(self.layoutWidget1)
        self.hue_flash_count_spin_box.setMinimum(1)
        self.hue_flash_count_spin_box.setMaximum(10)
        self.hue_flash_count_spin_box.setObjectName(_fromUtf8("hue_flash_count_spin_box"))
        self.gridLayout_3.addWidget(self.hue_flash_count_spin_box, 0, 1, 1, 1)
        self.formLayout.setLayout(6, QtGui.QFormLayout.LabelRole, self.gridLayout_3)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.test_connection_btn = QtGui.QPushButton(self.layoutWidget1)
        self.test_connection_btn.setObjectName(_fromUtf8("test_connection_btn"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.test_connection_btn)
        self.gridLayout_5.addWidget(self.test_connection_btn, 0, 0, 1, 1)
        self.test_flash_button = QtGui.QPushButton(self.layoutWidget1)
        self.test_flash_button.setObjectName(_fromUtf8("test_flash_button"))
        self.buttonGroup.addButton(self.test_flash_button)
        self.gridLayout_5.addWidget(self.test_flash_button, 1, 0, 1, 1)
        self.formLayout.setLayout(8, QtGui.QFormLayout.SpanningRole, self.gridLayout_5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(4, QtGui.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(7, QtGui.QFormLayout.LabelRole, spacerItem2)
        self.tabs.addTab(self.hue_tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabs)
        self.dialog_buttons = QtGui.QDialogButtonBox(Dialog)
        self.dialog_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.dialog_buttons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.dialog_buttons.setObjectName(_fromUtf8("dialog_buttons"))
        self.verticalLayout.addWidget(self.dialog_buttons)

        self.retranslateUi(Dialog)
        self.tabs.setCurrentIndex(1)
        QtCore.QObject.connect(self.dialog_buttons, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.dialog_buttons, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.tabs.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>", None))
        self.label.setText(_translate("Dialog", "Username", None))
        self.label_3.setText(_translate("Dialog", "OAuth", None))
        self.oauth_btn.setText(_translate("Dialog", "Get OAuth Token", None))
        self.label_2.setText(_translate("Dialog", "Channel", None))
        self.channel_text.setText(_translate("Dialog", "#", None))
        self.unlock_channel.setText(_translate("Dialog", "Unlock", None))
        self.test_connection_btn_2.setText(_translate("Dialog", "Test Connection", None))
        self.tabs.setTabText(self.tabs.indexOf(self.twitch_tab), _translate("Dialog", "Twitch", None))
        self.groupBox.setTitle(_translate("Dialog", "Hue Bridge IP", None))
        self.bridge_detect_btn.setText(_translate("Dialog", "Detect", None))
        self.unlock_2_check_2.setText(_translate("Dialog", "Unlock", None))
        self.label_6.setText(_translate("Dialog", "Flash Color 1", None))
        self.color_picker_1_btn.setText(_translate("Dialog", "Color Picker", None))
        self.unlock_1_check.setText(_translate("Dialog", "Unlock", None))
        self.unlock_2_check.setText(_translate("Dialog", "Unlock", None))
        self.label_7.setText(_translate("Dialog", "Flash Color 2", None))
        self.color_picker_2_btn.setText(_translate("Dialog", "Color Picker", None))
        self.label_8.setText(_translate("Dialog", "Flash Speed", None))
        self.label_9.setText(_translate("Dialog", "Flash Count", None))
        self.test_connection_btn.setText(_translate("Dialog", "Test Connection", None))
        self.test_flash_button.setText(_translate("Dialog", "Test Flash", None))
        self.tabs.setTabText(self.tabs.indexOf(self.hue_tab), _translate("Dialog", "Hue", None))

from PyQt4 import QtWebKit
